export const allProducts = [
  { id: 1, name: "BPC-157", description: "5mg Vial - Body protection compound", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 2, name: "TB-500", description: "5mg Vial - Thymosin beta-4", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 3, name: "GHK-CU", description: "50mg Vial - Copper peptide", price: 48, category: "Peptides", image: "/vial-3d.svg" },
  { id: 4, name: "GLP-1 SM", description: "10mg Vial - Semaglutide analog", price: 128, category: "GLP-1", image: "/vial-3d.svg" },
  { id: 5, name: "GLP-2 TZ", description: "10mg Vial - Tirzepatide analog", price: 184, category: "GLP-1", image: "/vial-3d.svg" },
  { id: 6, name: "GLP-3 RT", description: "10mg Vial - Retatrutide analog", price: 140, category: "GLP-1", image: "/vial-3d.svg" },
  { id: 7, name: "Glutathione", description: "600mg Vial - Antioxidant peptide", price: 54, category: "Peptides", image: "/vial-3d.svg" },
  { id: 8, name: "HCG", description: "5000iu Vial - Human chorionic gonadotropin", price: 40, category: "Research Chemicals", image: "/vial-3d.svg" },
  { id: 9, name: "IGF-1 LR3", description: "1mg Vial - Insulin-like growth factor", price: 75, category: "Peptides", image: "/vial-3d.svg", outOfStock: true },
  { id: 10, name: "KISSPEPTIN", description: "10mg Vial - Reproductive hormone peptide", price: 60, category: "Peptides", image: "/vial-3d.svg" },
  { id: 11, name: "KLOW", description: "Advanced healing peptide blend", price: 140, category: "Peptide Blends", image: "/vial-3d.svg" },
  { id: 12, name: "KPV", description: "10mg Vial - Anti-inflammatory tripeptide", price: 55, category: "Peptides", image: "/vial-3d.svg" },
  { id: 13, name: "Melanotan II", description: "10mg Vial - Melanocortin peptide", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 14, name: "MOTS-C", description: "10mg Vial - Mitochondrial peptide", price: 100, category: "Peptides", image: "/vial-3d.svg" },
  { id: 15, name: "NAD+", description: "500mg Vial - SALE PRICE", price: 85, originalPrice: 100, category: "Peptides", image: "/vial-3d.svg", onSale: true },
  { id: 16, name: "PT-141", description: "10mg Vial - Bremelanotide peptide", price: 40, category: "Peptides", image: "/vial-3d.svg" },
  { id: 17, name: "Selank", description: "10mg Vial - Nootropic peptide", price: 45, category: "Peptides", image: "/vial-3d.svg" },
  { id: 18, name: "Semax", description: "10mg Vial - Cognitive peptide", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 19, name: "Sermorelin", description: "5mg Vial - GHRH analog", price: 48, category: "Peptides", image: "/vial-3d.svg" },
  { id: 20, name: "Tesamorelin", description: "5mg Vial - GHRF analog", price: 45, category: "Peptides", image: "/vial-3d.svg" },
  { id: 21, name: "GHRP-6", description: "5mg Vial - Growth hormone releasing peptide", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 22, name: "CJC-1295", description: "5mg Vial - No DAC", price: 45, category: "Peptides", image: "/vial-3d.svg" },
  { id: 23, name: "Ipamorelin", description: "5mg Vial - GH secretagogue", price: 40, category: "Peptides", image: "/vial-3d.svg" },
  { id: 24, name: "DSIP", description: "5mg Vial - Delta sleep inducing peptide", price: 35, category: "Peptides", image: "/vial-3d.svg" },
  { id: 25, name: "AOD-9604", description: "5mg Vial - Fat loss peptide fragment", price: 50, category: "Peptides", image: "/vial-3d.svg" },
  { id: 26, name: "BPC-157/TB-500", description: "Blend - Healing & recovery combo", price: 75, category: "Peptide Blends", image: "/vial-3d.svg" },
  { id: 27, name: "CJC-1295/Ipamorelin", description: "5mg/5mg - GH releasing combo", price: 75, category: "Peptide Blends", image: "/vial-3d.svg" },
  { id: 28, name: "Glow", description: "GHK-CU, TB-500, BPC-157 blend", price: 115, category: "Peptide Blends", image: "/vial-3d.svg" },
  { id: 29, name: "SLU-PP-332", description: "10mg Vial - ERR agonist", price: 175, category: "Research Chemicals", image: "/vial-3d.svg" },
  { id: 30, name: "5% RU-58841", description: "30ml - Anti-androgen solution", price: 45, category: "Research Chemicals", image: "/vial-3d.svg" },
  { id: 31, name: "Enclomiphene", description: "12.5mg/ml - SERM", price: 75, category: "Research Chemicals", image: "/vial-3d.svg" },
  { id: 32, name: "Amino Tadalafil", description: "Liquid research compound 30ml", price: 54, category: "Research Chemicals", image: "/vial-3d.svg" },
  { id: 33, name: "BAC Water", description: "10ml - Bacteriostatic water", price: 12, category: "Lab Supplies", image: "/vial-3d.svg" },
  { id: 34, name: "Acetic Acid", description: "10ml - 0.6% solution", price: 10, category: "Lab Supplies", image: "/vial-3d.svg" },
];

export const categories = ["All", "Peptides", "GLP-1", "Peptide Blends", "Research Chemicals", "Lab Supplies"];
